### ISSUE TITLE
Game crashes if wta hotkey is pressed while in spectator mode with "Index out of Bounds" error

### ISSUE THREAD

**Issue by EltoCode** [TrueHorse/Wild-Tool-Access#27]
- Version: 1.20.1 Fabric 
- Mod Version: 1.5.1
- <details>   <summary>Crash Report: </summary> 

	``` Unreported exception thrown!
	java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
		at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
		at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
		at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
		at java.base/java.util.Objects.checkIndex(Objects.java:361)
		at java.base/java.util.ArrayList.get(ArrayList.java:427)
		at knot//net.trueHorse.wildToolAccess.AccessBar.selectItem(AccessBar.java:67)
		at knot//net.minecraft.class_329.closeOpenAccessbar(class_329.java:9510)
		at knot//net.trueHorse.wildToolAccess.WildToolAccessClient.onAccessBindingHeldStatusChanged(WildToolAccessClient.java:75)
		at knot//net.trueHorse.wildToolAccess.WildToolAccessClient.lambda$onInitializeClient$1(WildToolAccessClient.java:54)
		at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
		at knot//net.minecraft.class_310.handler$bdn000$fabric-lifecycle-events-v1$onEndTick(class_310.java:7522)
		at knot//net.minecraft.class_310.method_1574(class_310.java:1957)
		at knot//net.minecraft.class_310.method_1523(class_310.java:1181)
		at knot//net.minecraft.class_310.method_1514(class_310.java:802)
		at knot//net.minecraft.client.main.Main.main(Main.java:250)
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

- Steps to reproduce: 
Load the mod into the respective version
Set config to toggle
Switch into spectator mode and use the hotkey to open the wta menu

- Suggested Fix: Add a check that prevents the wta menu from opening if the player is in spectator mode.

**Comment by TrueHorse** [comment]
Thank you for the report and a professional looking one at that. 🙂
Is this inpacting/bothering you a lot? Because if not I would fix it together with something else when it comes up, rather than uploading a new build just for that fix.

**Comment by EltoCode** [comment]
I really liked your mod lol, giving a good report is the least i could do.

ahh no its cool. its just i've set the key to alt, so the game always crashes when i try to alt tab out in spec, but its manageable.

**Comment by TrueHorse** [comment]
Just did it anyway. Not like I have anything better to do. ::Kappa::

And in the process I made the life of cheaters easier (at least thats the only use case I can think of), but wellp. Just have to hope people are sensible. People play for fun after all.

**Comment by EltoCode** [comment]
haha thanks! wdym making it easy for cheaters? but yeah hope it doesn't happen.
